### PR TITLE
Added "Stop on HALT instruction" option to the "Debug" pull-down menu.

### PR DESCRIPTION
**Pull request by iratahack**
The Z80 'halt' instruction is used extensively in programming games to make the system wait for VBLANK or VLINE interrupts before updating video memory.

Currently the debugger stops program execution each time the Z80 executes a 'halt' instruction making debugging impossible.

The PR adds a new option to the Debug pull-down to "Stop on HALT instruction"

### CODE REVIEW

**Comment by RevCurtisP** [comment]
This should be an option in the debug dropdown menu
`Stop on HALT instruction`
Default to off when no config file is found.

**Comment by iratahack** [comment]
> This should be an option in the debug dropdown menu `Stop on HALT instruction` Default to off when no config file is found.

Thanks for the feedback, Curtis. I'll see about updating to PR to handle it this way.
IH.

**Comment by iratahack** [comment]
@RevCurtisP , please take a look at this updated PR.
Thanks.

**Comment by fvdhoef** [comment]
I've merged your changes. Thanks!

**Pull request merged**
